### ISSUE TITLE
[FEATURE]: use shiki syntax highlighter in ComponentPreview

### ISSUE THREAD

**Issue by Ansub** [Ansub/SyntaxUI#101]
### Feature Description 📝

remove `react-syntax-highlighter` and add `shiki` instead in `src/components/ComponentPreview.tsx`

**Comment by krishpatel023** [comment]
I'll look into it

**Comment by krishpatel023** [comment]
Hey @Ansub , I was able to fix the component using shiki but the mdx part of the code display broke as its running the older version (v 0.14.0) and the component requires the new version(v 1.3.0). You will need to migrate that to the latest version before I can add this.

[https://shiki.style/guide/migrate](https://shiki.style/guide/migrate)

**Comment by Ansub** [comment]
I tried refactoring and it's breaking a lot of things

**Comment by krishpatel023** [comment]
Same here, I also tried doing that but there is not enough documentation for the migration and usage.

**Comment by Ansub** [comment]
I will be deprecating Shiki. It has become a burden at this point

how can i get the same code highlighting like i have in shiki any idea?

**Comment by krishpatel023** [comment]
Give me a day to look that up. I'll update you tomorrow.

**Comment by krishpatel023** [comment]
Hey @Ansub , [Code-Hike](https://codehike.org/) is the best way that we can do this. Lets keep shiki in the component code display and for mdx code block we use code-hike.

**Comment by epoll31** [comment]
@Ansub I got shiki 1.3.0 working with CodeGroup, CodeGroupFromFile, ComponentPreview, and normal backticks (including inline). Do you still want to stop using shiki?

**Comment by Ansub** [comment]
@krishpatel023 you can check this implementation which @epoll31 , it was a great learning for me aswell.

**Comment by krishpatel023** [comment]
Hey @Ansub, Yeah i saw the code and it was great to know the implementation. sorry I couldn't contribute and sorry for the late reply :)

**Comment by Ansub** [comment]
No worries, it's a learning experience for all of us in the end.

That's the best part about open-source
