### ISSUE TITLE
[BUG]: BackgroundShift component in Pricing should not have a key

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#111]
### Description 📝

Keys can be placed on React components without explicitly adding them as props. We should remove this key from the props as it gives an error.

<img width="481" alt="Screenshot 2024-04-30 at 12 19 04 AM" src="https://github.com/Ansub/SyntaxUI/assets/16091805/cb43042e-06a9-40c4-8621-d652d321e0a8">

### Link 🔗

https://syntaxui.com/docs/components/pricing

### Steps to Reproduce 🔄

1. go to https://syntaxui.com/docs/components/pricing

### Screenshots 📸

<img width="444" alt="Screenshot 2024-04-30 at 12 22 56 AM" src="https://github.com/Ansub/SyntaxUI/assets/16091805/49178240-57a0-431c-8500-d26a82f1dbe4">
<img width="481" alt="Screenshot 2024-04-30 at 12 19 04 AM" src="https://github.com/Ansub/SyntaxUI/assets/16091805/db2f85ca-c8d6-4510-96af-b66335781f86">

### Expected Behavior 🤔

props should not have key

### Actual Behavior 😱

props has key

### Environment 🌍

n/a

**Comment by Ansub** [comment]
fixed in [a685831](https://github.com/Ansub/SyntaxUI/commit/a6858311933be49c16dd203e8851bfbca4949f38)
