### ISSUE TITLE
[BUG]: Pull Request Template Issue

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#121]
### Description 📝

The following section should be removed from the Pull Request Template

```
---
name: Pull Request
about: Create a pull request syntaxUI
title: ''
labels: ''
assignees: ''
---
```

### Link 🔗

https://github.com/Ansub/SyntaxUI/blob/b79cff4685c56c41edac1ac1c3e2e65556073ac4/.github/pull_request_template.md?plain=1

### Steps to Reproduce 🔄

Go To: https://github.com/Ansub/SyntaxUI/blob/b79cff4685c56c41edac1ac1c3e2e65556073ac4/.github/pull_request_template.md?plain=1

### Screenshots 📸

<img width="284" alt="Screenshot 2024-05-01 at 11 30 56 PM" src="https://github.com/Ansub/SyntaxUI/assets/16091805/7c4d4c41-7b9e-488b-a82f-0fa1fa2a4462">

### Expected Behavior 🤔

The header should not be there.

### Actual Behavior 😱

The header is there.

### Environment 🌍

n/a

**Comment by Ansub** [comment]
resolved in b750d5fa63120494cd698dc40d573550ee11798b
