### ISSUE TITLE
[BUG]: Empty Keyword get added on enter

### ISSUE THREAD

**Issue by adii1203** [Ansub/SyntaxUI#125]
### Description 📝

Empty keyword get added when you press enter without typing anything.

### Link 🔗

https://syntaxui.com/docs/components/input

### Steps to Reproduce 🔄

1. Go to https://syntaxui.com/docs/components/input
2. Press enter in the input field without typing anything

### Screenshots 📸

https://github.com/Ansub/SyntaxUI/assets/114096753/ee3ffa98-e476-406f-987e-7df271dd3d24

### Expected Behavior 🤔

on Enter don't do anything when the input value is empty (`' '`) 

### Actual Behavior 😱

The empty keyword gets added on Enter when the input field is empty.

### Environment 🌍

- Browser

**Comment by Ansub** [comment]
oops, you are fixing it?

**Comment by adii1203** [comment]
I can, if you say

**Comment by Ansub** [comment]
all yours :)
