### ISSUE TITLE
[FEATURE]: ditch `/docs` path

### ISSUE THREAD

**Issue by Ansub** [Ansub/SyntaxUI#143]
### Feature Description 📝

I am thinking of ditching `/docs` pathname, `Get Started` will get redirected to `/components` page which is basically `/docs` atm. 

### Motivation 🌟

Link sharing will become much easier. `docs` makes it appear overly complex, which seems unnecessary.

### Expected Behavior 🤔

instead of redirection to `https://syntaxui.com/docs`  it will be `https://syntaxui.com/components`

**Comment by PoulavBhowmick03** [comment]
Hey! Can I add this on the website? Would love to contribute to SyntaxUI and get started with this

**Comment by Ansub** [comment]
sure, all yours

**Comment by epoll31** [comment]
We should implement this in a way that supports redirects from old urls to maintain backwards compatibility?

**Comment by Ansub** [comment]
yeah that should definitely be there, maybe you two can collaborate on this one. i think @epoll31 you can lead this one as this is a big change and you have more experience with the codebase of SyntaxUI

**Comment by PoulavBhowmick03** [comment]
https://github.com/Ansub/SyntaxUI/assets/133862694/97144086-44ac-4b64-9210-7d0ebe601535

Does this work? Or should there be more changes required

**Comment by Ansub** [comment]
path is wrong, it should be for eg. `components/loaders` instead of `components/components/loaders`

**Comment by epoll31** [comment]
@Ansub for this part:
> instead of redirection to `https://syntaxui.com/docs` it will be `https://syntaxui.com/components`

Do you want `https://syntaxui.com/components` to look like `https://syntaxui.com/docs`

In that case we would move the `page.tsx` from `docs/` into `components/`

**Comment by vanshavenger** [comment]
The Simple solution for the above can be making docs as (docs) and adding a page to all routes -> Components, animations, effects and hooks where we can say that a user can select a component from the sidebar to view it.

as otherwise if no pages.tsx made it will give a 404 error

**Comment by Ansub** [comment]
basically (docs) can what @vanshavenger suggested

then we can have redirections for components, effects, animations

eg. “syntaxui.com/components/button”,

**Comment by epoll31** [comment]
Ya that's basically what I had implemented in the PR :)
