### ISSUE TITLE
[FEATURE]: Add a color inversion button in the /docs/components/button

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Ansub/SyntaxUI#149]
### Feature Description 📝

A color inversion button where, on hovering, the color of the text and the button inverts 

### Motivation 🌟

This is widely used in many projects and users seem to prefer for navigation or other purposes

### Expected Behavior 🤔

![image](https://github.com/Ansub/SyntaxUI/assets/133862694/4b43d832-d36c-4da0-8574-ae8e8e5c1f40)
Before hover
![image](https://github.com/Ansub/SyntaxUI/assets/133862694/8b7aac0e-b17b-469d-9dc9-ff48af42b7ca)
After hover

**Comment by Ansub** [comment]
can ypu share a http://play.tailwindcss.com for this?

**Comment by PoulavBhowmick03** [comment]
Hi, I am not able to run it there since this is a jsx code, you can check this video for reference 

https://github.com/Ansub/SyntaxUI/assets/133862694/27c4d687-507e-4f5c-bf45-449b7226e676

**Comment by Ansub** [comment]
This appears similar to the content I included today, so I will refrain from [adding  it.](https://syntaxui.com/docs/components/button/gradient-fill-button)
