### ISSUE TITLE
Remove white background from bounce loader

### ISSUE THREAD

**Issue by Ansub** [Ansub/syntaxUI#15]
Bounce Loader has a white background (it is a little hard to see in screenshot below but it's there) that is compromising its aesthetics.

https://syntaxui.com/docs/components/loaders/bounce

![CleanShot 2024-03-29 at 23 53 15@2x](https://github.com/Ansub/syntaxUI/assets/12985873/7e23895d-9dbb-4da6-b4b5-519b14757387)

**Comment by mateoetchepare** [comment]
hello man, just fixed the issue. give me 5 min and i'll upload the PR

**Comment by Ansub** [comment]
#17 is merged hence closing this issue. 

Thank you @mateoetchepare
