### ISSUE TITLE
[BUG]: expand/collapse button broken hover effect

### ISSUE THREAD

**Issue by mezotv** [Ansub/SyntaxUI#152]
### Description 📝

When hovering over the expand/collapse button the text under it turns unreadable

### Link 🔗

https://syntaxui.com/docs/animations/skewed-infinite-scroll

### Steps to Reproduce 🔄

1. Go to https://syntaxui.com/docs/animations/skewed-infinite-scroll 
2. Scroll down to the expand button in the code view
3. Hover over it

### Screenshots 📸

![image](https://github.com/Ansub/SyntaxUI/assets/68947960/28e4b643-b346-4e26-a470-6c8ac77cde70)
![bug](https://github.com/Ansub/SyntaxUI/assets/68947960/e58b2d26-4868-4b26-aa74-42c232d42ecf)

### Expected Behavior 🤔

The button has a hover effect thats inline with the branding

### Actual Behavior 😱

The hover effect is applied to the background and makes the code under it unreadable

### Environment 🌍

Firefox - Windows 11

**Comment by mezotv** [comment]
I got a fix ready for this once you approve @Ansub!

**Comment by epoll31** [comment]
@mezotv 

in `src/components/code/CodeGroup.tsx`, in this button:
```
<Button className="w-xs absolute bottom-0 left-0 right-0 block rounded-2xl bg-transparent p-0 text-sm font-medium text-white"
  onClick={() => setMinimized(!minimized)}
>
  {minimized ? 'Expand' : 'Collapse'}
</Button>
```

adding `w-full` to the `className` instead of `w-xs` will solve the centering issue in firefox. This way we can make sure that it's centered on all browsers.

**Comment by mezotv** [comment]
> adding `w-full` to the `className` instead of `w-xs` will solve the centering issue in firefox. This way we can make sure that it's centered on all browsers.

I made sure to add that, thank you!

**Comment by Ansub** [comment]
fixed here: https://github.com/Ansub/SyntaxUI/commit/7118b8b428eda1c26a0c5b0d958e16648b0d9a01
