### ISSUE TITLE
[BUG]: Footer should always stay at the bottom 

### ISSUE THREAD

**Issue by Ansub** [Ansub/SyntaxUI#159]
### Description 📝

When navigating to a component that doesn't fill the entire viewport, the footer appears at the top instead of staying at the bottom as expected.

### Link 🔗

https://syntaxui.com/docs/components/button/3d-button

### Screenshots 📸

![CleanShot 2024-05-07 at 13 58 24@2x](https://github.com/Ansub/SyntaxUI/assets/12985873/6ac7fdd2-73d1-4693-b896-94ad2799d1fe)

**Comment by shrix1** [comment]
it should be a easy fix, i will take a look into it
