### ISSUE TITLE
[BUG]: Navbar Mobile responsive issue 

### ISSUE THREAD

**Issue by shrix1** [Ansub/SyntaxUI#162]
### Navbar Mobile responsive issue 

<img width="355" alt="Screenshot 2024-05-07 at 6 04 56 PM" src="https://github.com/Ansub/SyntaxUI/assets/92677078/3a4706a2-fc92-4f9b-938f-c5814a109711">

<img width="352" alt="Screenshot 2024-05-07 at 6 05 11 PM" src="https://github.com/Ansub/SyntaxUI/assets/92677078/4d382b4a-a9ad-444d-b84c-f11645a40537">

These are the routes:
- https://syntaxui.com/ 
- https://syntaxui.com/docs/components/button/border-rotate-button and **/docs/components/button/:path**

### Fix should something look like this:
@Ansub Please add the correct UI for the mobile view navbar

<img width="336" alt="Screenshot 2024-05-07 at 5 59 47 PM" src="https://github.com/Ansub/SyntaxUI/assets/92677078/f5659e43-0f90-4dfa-87ee-67d0420879ca">

<img width="358" alt="Screenshot 2024-05-07 at 6 02 32 PM" src="https://github.com/Ansub/SyntaxUI/assets/92677078/90cfe847-2c03-446c-825c-7eebdce569d0">

## Link 🔗

https://syntaxui.com/

**Comment by Ansub** [comment]
we can simply hide the SyntaxUI text on smaller screens
