### ISSUE TITLE
[FEATURE]: Make Sitemap dynamic

### ISSUE THREAD

**Issue by Ansub** [Ansub/SyntaxUI#167]
### Feature Description 📝

sitemap should be made so that we don't have to add every link inside sitemap for google to index, we can follow this [guide](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generating-a-sitemap-using-code-js-ts) by Next.js for doing it.

**Comment by shrix1** [comment]
I will take a look into it.

**Comment by epoll31** [comment]
@shrix1 How's it going? I was curious about this so I worked on an implementation.
I got mine working. 
Do you want to compare?
