### ISSUE TITLE
[BUG]: Change images:domain to images: remotePatterns 

### ISSUE THREAD

**Issue by shrix1** [Ansub/SyntaxUI#181]
### Description 📝

- Change `images : {domain :["//"]}` to `images: remotePatterns` 
Refer : https://nextjs.org/docs/messages/next-image-unconfigured-host

Because `images:domain` is deprecated 

### Link 🔗

https://nextjs.org/docs/messages/next-image-unconfigured-hos

### Screenshots 📸

n/a

**Comment by 0xyosef** [comment]
Ok i will try to do it 🫡
