### ISSUE TITLE
🐞 Prettier is not formatting code in mdx files

### ISSUE THREAD

**Issue by Ansub** [Ansub/SyntaxUI#24]
**Describe the bug**
if i am making a change in `CodePreview` component in any .mdx file then prettier won't format that string literal code.

i manually have to format it using tabs and backspaces.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any `mdx` file
2. Make changes in `CodePreview` component and save change
4. You will see code is not getting formatted

**Comment by dakshsinghrathore** [comment]
Surprisingly, even on [Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAkMOCMICEBDAL3wF98AzHCdU-AcgDoB6AMVQAeMAK4447ADpQM2PPhJlhNOkSYsOPfkNHipUuANkF8kKAGdjjCBFIBeeVMIALVEjYADXsIAmAczj4ACTAlFSc3qhmmAA2FACeAHIU6AEAPqkcoey07gA0jvgUwjBOuGZuANoFROxMcN7s+VBsLexmFNHRcZLNRAC6UrR6UADE+AAScJ0QuaQA7rjR3gCEw44AkuysFM0Uc3BmLAGEmBQ4FL7nmE6cwwA8ywC0j-ib2yYsKbD4zwB897xrPgAEa+WzsMQNf69Uh3Sg4Ui-Fyw7jw6EteTOKbRGwtIYw0gkUjcABUhSgEBKcARkHQXwIJO4+LufGs0Kk7k5UngFg+3jgwJxYAA1hyuVAxe4AFZmKToCDeYTROCcAxGMz4ezsHkwHqc9zDfVmJxSKCYVioH6+KwQSXDDIAFQOxkdFEFx3wqSkGSISGeL1IGT9-sIXqgPvwAGEINEAIyhqMxgBMgeGatwln5DCK0UshAAFMAwC4lmIYbQAJSa374O74CIAN1+RMIxdQpYQtBZjehIFyIAgmBgqGgZmQoDOzDmAAUzggxygOnN4mP+8DziK4DAAMrJOAAGVQUDgyGz0TMcDXG+FW+3pzAR98yBgOGEl5AF-QqGfr-faupGAIDAHROjgUBnKgBynh0F79mYj7KgAisIlInkgZ6wSAMoCNuCFwMhqHQee74AI4ofA07MJgC4gBQZiPMe9T1H2IAvhQ7aPtGdIUMgtGdCx8FQL4yoAIIwC+qDAsUcDTtSh7HkRmFODA6DRAA6i4PL3nA27zqgw4NvpcS8WAZiriADZvusUD8rA25gDgqBDiJNnbjAcTKop76YMwF5qVcvE+Qc1INie-ZHheeCURc6A8ehMHeWckW8eg3gCCxPlHjAamoN4JTIAAHAADP2YhkagYjRb4sVef2wHAjleVOMgSb9sIF4Om6C4YX+6DAvU-LePuOy+MIFxwICOCxeJj68UUMAQCAtC0EAA) we can encounter this issue,

[issue#24.webm](https://github.com/Ansub/SyntaxUI/assets/115932772/11669f00-7ea7-4c1c-b87e-535e1c5d799e)

@Ansub 

Additionally I encountered that prettier version wasn't up to date, so updated it, which in return fixed formatting of text inside mdx files.

**Comment by Ansub** [comment]
Fixed this problem by making a new component called: `ComponentPreview.tsx`
