### ISSUE TITLE
🐞: Text Ticker has incorrect labels and page name

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#35]
**Describe the bug**
The sidebar navigation and homepage component list labels for 'Text Ticker' just says 'Text'. This might have been done for a reason, but I was expecting to see a basic Text component, which is different from a Text Ticker component. Also, the [component page](https://syntaxui.com/docs/components/text)'s URL is `/text` instead of `/text-ticker`.

**To Reproduce**

- From the [homepage](https://syntaxui.com/)
    1. View `Text` component label
    2. Click on the 'Text' component
    3. The page now displays the 'Text Ticker' component
- From the [any component page](https://syntaxui.com/docs/components/text)
    1. View `Text` navigation label in the sidebar
    2. Click on the 'Text' label
    3. The page now displays the 'Text Ticker' component

**Expected behavior**
I expected the to see a basic Text component instead of a Text Ticker component.

**Screenshots**
Home Page Example
<img width="1172" alt="image" src="https://github.com/Ansub/SyntaxUI/assets/16091805/ba38fc42-4d21-4424-b624-438dfa10e2b0">
Docs Component Page Example
<img width="1198" alt="image" src="https://github.com/Ansub/SyntaxUI/assets/16091805/08e94207-3e11-4c8b-95c9-3c8ad9a5ba67">

**Additional context**
I believe that a great fix for this could be to change the route from `/text` to `/text-ticker` and to rename the labels from `Text` to `Text Ticker`

**Comment by Ansub** [comment]
Made a comment on this PR

https://github.com/Ansub/SyntaxUI/pull/36#issuecomment-2051200116
