### ISSUE TITLE
✨: useMediaSizes Hook for displaying components conditionally.

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#38]
**Is your feature request related to a problem? Please describe.**
Sometimes, you want to change an element's props or placement in the component hierarchy depending on the size of the window screen.

**Describe the solution you'd like**
I would like to add a hook named `useMediaSizes` that comes with the sm, md, lg, and xl breakpoints by default but allows the user to specify additional custom breakpoints with the type `{ [name: string]: number }`. It will then return an object that is of type: `{ [name: string]: boolean }` that represents the current state of the breakpoints including the defaults and all custom breakpoints.

**Comment by epoll31** [comment]
I already have the code for this, but I would be happy to whip up an example for the `Hooks` section of the page.

**Comment by Ansub** [comment]
can you give an example scenario where i can use this hook?

**Comment by epoll31** [comment]
An example where I have used it is [the Education page on my personal website](https://epoll31.github.io/education).

Here I have a Side Bar that shows up on the left side when there is room, but when there is no room it places in above the page content. So for my education page I put some filters in my side bar, but when on mobile, I don't want the filters to appear before the title of my main content, so i place the item in the sidebar conditionally if there is enough room and in the middle of the main content when that condition isn't met.

Here there is enough room, so it is displayed in the sidebar:
<img width="926" alt="image" src="https://github.com/Ansub/SyntaxUI/assets/16091805/5717cfa6-2584-44e2-9ea5-25d8d1c47bad">

Here there is not enough room, so it is displayed just above the cards:
<img width="538" alt="image" src="https://github.com/Ansub/SyntaxUI/assets/16091805/85baa9b4-5947-4459-a3bc-d43cc187c40f">

**Comment by Ansub** [comment]
correct me if i'm wrong but can't we achieve the same thing with [tailwind css breakpoints](https://tailwindcss.com/docs/responsive-design)?

**Comment by epoll31** [comment]
You can achieve a similar result, but in that case you would have two Filter components where one is hidden and one is visible, using the hook you can make it so that there is only one component at a time.

**Comment by Ansub** [comment]
sure you can add it then, i will also have a look at this hook. 

looks quite interesting
