### ISSUE TITLE
✨: Create issue forms for respective buttons

### ISSUE THREAD

**Issue by dakshsinghrathore** [Ansub/SyntaxUI#69]
**Is your feature request related to a problem? Please describe.**

Currently, we lack issue forms which is kinda crucial in making the whole process of raising an issue smooth for newbie contributors

**Describe the solution you'd like**

![image](https://github.com/Ansub/SyntaxUI/assets/115932772/a9237316-0036-459b-a0fe-51c4deec6f00)

**Describe alternatives you've considered**
NULL

**Additional context**

**Comment by Ansub** [comment]
this actually makes sense, thanks for this idea. 

if you have the template ready can you raise a PR for this?

**Comment by dakshsinghrathore** [comment]
@Ansub yes will be raising one shortly.

**Comment by epoll31** [comment]
@dakshsinghrathore This is pretty cool

**Comment by epoll31** [comment]
@dakshsinghrathore Can you still upload photos in the forms?

**Comment by dakshsinghrathore** [comment]
Yes @epoll31 check [this out](https://github.com/dakshsinghrathore/Brighter-Beginnings/issues/new?assignees=&labels=Feat%2CNeeds+Triage%2CSWOC24&projects=&template=feature.yaml&title=Feat%3A)

**Comment by epoll31** [comment]
That's neat! I didn't realize those were md fields.

**Comment by dakshsinghrathore** [comment]
@epoll31 github recently added this [feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), do give it a read.

**Comment by Ansub** [comment]
#72

**Comment by Ansub** [comment]
Merged PR #72
