### ISSUE TITLE
[🐞 BUG]: Fix .github/ISSUE_TEMPLATE/Chore.yml

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#75]
### Description 📝

From GitHub:

There are some problems with this template

assignees must be of type String or Array. [Learn more about error 1.](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#key-must-be-a-string)

about is not a permitted key. [Learn more about error 2.](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#input-is-not-a-permitted-key)

From Me:
- Remove `assignees`
- Change `about` to `description`

### Link 🔗

https://github.com/Ansub/SyntaxUI/blob/main/.github/ISSUE_TEMPLATE/chore.yml

### Steps to Reproduce 🔄

1. Go To https://github.com/Ansub/SyntaxUI/blob/main/.github/ISSUE_TEMPLATE/chore.yml

### Screenshots 📸

<img width="457" alt="image" src="https://github.com/Ansub/SyntaxUI/assets/16091805/2abf5332-5923-44db-b2cd-ad2a12e5b7fb">

### Expected Behavior 🤔

It should not errror

### Actual Behavior 😱

It errors

### Environment 🌍

na

**Comment by Ansub** [comment]
We are not adding a chore template at the moment. You can delete the file for this. A bug report is sufficient for this, and the user can then request that I add the "chore" label to it.
