### ISSUE TITLE
[✨ FEATURE]:  Automate issue labelling process

### ISSUE THREAD

**Issue by dakshsinghrathore** [Ansub/SyntaxUI#77]
### Feature Description 📝

I'm considering _automating_ the process of _labeling issues._ With this setup, when an issue is created, a **GitHub Actions bot** will promptly apply **appropriate** labels, thus saving valuable **time** for maintainers.

### Motivation 🌟

Every **developer** desires to **automate** their **routine** tasks, saving significant time. Additionally, labeling every issue in a repository can become quite **_monotonous_**. 🥲 

### Expected Behavior 🤔

**_DO WATCH TILL END_**

[Screencast from 26-04-24 04:12:54 AM IST.webm](https://github.com/Ansub/SyntaxUI/assets/115932772/67f1c582-35cd-4bba-a05a-6f12a435f3d0)

### Additional Information ℹ️

will be pulling an all nighter to code this 😅

**Comment by epoll31** [comment]
@dakshsinghrathore Can you close this when you get a chance?
