### ISSUE TITLE
[FEATURE]: Add github actions for greeting contributors

### ISSUE THREAD

**Issue by dakshsinghrathore** [Ansub/SyntaxUI#89]
### Feature Description 📝

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

### Motivation 🌟

This year, I served as a project admin for [BrighterBeginnings](https://github.com/dakshsinghrathore/Brighter-Beginnings) in SWOC24. The project attracted numerous new contributors, making it challenging for me to personally greet each one and remind them of the contribution guidelines when they created an issue. Consequently, I felt the need to automate this process.

### GH bot, making comment under issue ⬇️ 

![image](https://github.com/Ansub/SyntaxUI/assets/115932772/ec88ad10-c7eb-44ca-864c-06d45ddad1f1)

### GH bot, making comment under PR ⬇️ 

![image](https://github.com/Ansub/SyntaxUI/assets/115932772/b2a255e6-ef4a-4bde-8e9a-0f9acb49430c)

### Additional Information ℹ️

To implement this feature, I'll create a file named greetings.yaml within the workflows folder.

**Comment by Ansub** [comment]
instead of this github logo can i get my profile picture in it to make it appear more human like? 😜

**Comment by dakshsinghrathore** [comment]
@Ansub Unfortunately it isn't possible, read full explanation[ here](https://github.com/orgs/community/discussions/26871)
