### ISSUE TITLE
[BUG]: Tabs are disorganized

### ISSUE THREAD

**Issue by epoll31** [Ansub/SyntaxUI#95]
### Description 📝

The files related to Tabs are very disorganized.

### Link 🔗

n/a

### Steps to Reproduce 🔄

n/a

### Screenshots 📸

n/a

### Expected Behavior 🤔

Tabs should be organized into the following structure:
```
.
└── showcase/
    └── components/
        └── tabs/
            ├── ButtonShapeTabs.tsx
            ├── IconTabs.tsx
            ├── LineTabs.tsx
            ├── SimpleTabs.tsx
            └── Tabs.tsx
```

### Actual Behavior 😱

Some files are still in `src/ui` and some are in `src/components/showcase`.

### Environment 🌍

n/a

**Comment by epoll31** [comment]
@Ansub can you assign this as a chore?

**Comment by Ansub** [comment]
fixed in 11dff11c3271734b002b47e5284257cc4bdb7017

**Comment by Ansub** [comment]
btw @epoll31 instead of bug if you mention chore it will assign `chore` tag to it

**Comment by epoll31** [comment]
@Ansub Interesting, i didn't know that.

What do you mean by mention? like if i write the word in the description?

**Comment by epoll31** [comment]
Just looked at the workflow and now I understand. That's a pretty neat feature
